# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

plugins:
    - jekyll-paginate
    - jekyll-sitemap

permalink:           /:title:output_ext

# Setup
title:              brandontreb.com
tagline:             'Tips And Resources For Software Consultants'
description:         'A blog about software development consulting'
url:                 'http://brandontreb.com'
baseurl:             ''

paginate: 25
paginate_path: "page:num"

# About/contact
author:
  name:              Brandon Trebitowski
  url:               https://twitter.com/brandontreb
  email:             brandon@pixegon.com

# Custom vars
version:             1.0.0

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "post"
