# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.

gems: 
    - jekyll-paginate
    - jekyll-sitemap

permalink:           pretty

# Setup
title:              brandontreb.com 
tagline:             'Tips And Resources For Software Consultants'
description:         'A blog about software development consulting' 
url:                 'http://brandontreb.com'
baseurl:             ''             

paginate: 5
paginate_path: "page:num"

# About/contact
author:
  name:              Brandon Trebitowski
  url:               https://twitter.com/brandontreb
  email:             brandon@pixegon.com

# Custom vars
version:             1.0.0
